- name: create deploy user
  user: name={{ ansible_user }} shell=/bin/bash append=true

- name: add deploy user public key to authorized_keys
  authorized_key: user={{ ansible_user }} key=https://github.com/{{ gh_pubkey_user }}.keys

- name: add deploy user to sudoers
  lineinfile:
    "dest=/etc/sudoers
    regexp='^{{ ansible_user }} ALL'
    line='{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL'
    state=present"